apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: dev
  annotations:
    cloud.google.com/backend-config: '{"default": "cloud-armor-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
    - port: 80
      targetPort: 3000
